name: Links

on:
  push:
    paths:
      - '**/*.html'
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.html'
      - '**/*.md'
  schedule:
    - cron:  '0 0 * * SUN'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress **/*.md **/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

#      - name: Create Issue From File
#        uses: peter-evans/create-issue-from-file@v3
#        with:
#          title: Link Checker Report
#          content-filepath: ./lychee/out.md
#          labels: report, automated issue
